package com.mycompany.exoreptilia;

/**
 * @author diana
 */
public class PanelClientes extends javax.swing.JPanel {
    //FormPrincipal fp = new FormPrincipal();
    private FormPrincipal fp;
    
    public PanelClientes() {
        initComponents();
    }
    
    public PanelClientes(FormPrincipal fp){
        this.fp = fp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnFrecuente = new javax.swing.JButton();
        BtnConfiable = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnFrecuente.setText("CLIENTES FRECUENTES");
        BtnFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFrecuenteActionPerformed(evt);
            }
        });
        add(BtnFrecuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 230, 110));

        BtnConfiable.setText("CLIENTES CONFIABLES");
        add(BtnConfiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 230, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFrecuenteActionPerformed
        // TODO add your handling code here:
        fp.MostrarPanelConsultaClientes();
    }//GEN-LAST:event_BtnFrecuenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfiable;
    private javax.swing.JButton BtnFrecuente;
    // End of variables declaration//GEN-END:variables
}
